name: Deploy DERS API to Dev Server

on:
  workflow_call:
    secrets:
      DEV_SERVER_PASSWORD:
        required: true
    inputs:
      PROJECT_NAME:
        type: string
        required: true

jobs:
  deploy-latest-release-on-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Execute docker-compose remotely via ssh
        uses: appleboy/ssh-action@master
        env:
          IMAGE_NAME: sastechnologies/${{ inputs.PROJECT_NAME }}:latest
          DERS_SECURITY_FIREBASE_SERVICE_KEY: ${{ secrets.DERS_SECURITY_FIREBASE_SERVICE_KEY }}
          AZURE_STORAGE_CONNECTION_STRING_DEV: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING_DEV }}
        with:
          host: 86.120.169.27
          username: github-actions
          password: ${{ secrets.DEV_SERVER_PASSWORD }}
          envs: IMAGE_NAME
          script: |
            export IMAGE_NAME=$IMAGE_NAME
            cd /opt/arctic-stream/dev
            docker-compose down --remove-orphans
            if [[ "$(docker images -q myimage:mytag 2> /dev/null)" == "" ]]; then
              docker image rm $IMAGE_NAME 
            fi
            docker-compose up -d --no-deps
