name: Deploy DERS API to Dev Server

on:
  workflow_call:
    secrets:
      REMOTE_SERVER_HOST:
        required: true
      REMOTE_SERVER_PASSWORD:
        required: true

jobs:
  deploy-latest-release-on-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Execute docker-compose remotely via ssh
        uses: appleboy/ssh-action@master
        with:
          username: github-actions
          host: ${{ secrets.REMOTE_SERVER_HOST }}
          password: ${{ secrets.REMOTE_SERVER_PASSWORD }}
          script: |
            cd /opt/arctic-stream
            docker-compose down
            docker-compose up -d --pull
