name: Deploy DERS API to Dev Server

on:
  workflow_call:
    secrets:
      AZURE_STORAGE_CONNECTION_STRING_DEV:
        required: true
      DERS_SECURITY_FIREBASE_SERVICE_KEY:
        required: true
      DEV_SERVER_PASSWORD:
        required: true
    inputs:
      PROJECT_NAME:
        required: true

jobs:
  deploy-latest-release-on-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Execute docker-compose remotely via ssh
        uses: appleboy/ssh-action@master
        env:
          IMAGE_NAME: sastechnologeis/${{ inputs.PROJECT_NAME }}:latest
          DERS_SECURITY_FIREBASE_SERVICE_KEY: ${{ secrets.DERS_SECURITY_FIREBASE_SERVICE_KEY }}
          AZURE_STORAGE_CONNECTION_STRING_DEV: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING_DEV }}
        with:
          host: 86.120.169.27
          username: github-actions
          password: ${{ secrets.DEV_SERVER_PASSWORD }}
          envs: IMAGE_NAME,DERS_SECURITY_FIREBASE_SERVICE_KEY,AZURE_STORAGE_CONNECTION_STRING_DEV
          script: |
            export IMAGE_NAME=$IMAGE_NAME
            export DERS_SECURITY_FIREBASE_SERVICE_KEY=$DERS_SECURITY_FIREBASE_SERVICE_KEY
            export AZURE_STORAGE_CONNECTION_STRING_DEV=$AZURE_STORAGE_CONNECTION_STRING_DEV
            cd /opt/ders
            docker image rm $IMAGE_NAME 
            docker-compose up -d --no-deps
