name: Deploy DERS API to Dev Server

on:
  workflow_call:
    secrets:
      DEV_SERVER_HOST:
        required: true
      DEV_SERVER_PASSWORD:
        required: true

jobs:
  deploy-latest-release-on-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Execute docker-compose remotely via ssh
        uses: appleboy/ssh-action@master
        env:
          DERS_SECURITY_FIREBASE_SERVICE_KEY: ${{ secrets.DERS_SECURITY_FIREBASE_SERVICE_KEY }}
          AZURE_STORAGE_CONNECTION_STRING_DEV: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING_DEV }}
        with:
          host: ${{ secrets.DEV_SERVER_HOST }}
          username: github-actions
          password: ${{ secrets.DEV_SERVER_PASSWORD }}
          script: |
            cd /opt/arctic-stream
            docker-compose down
            docker-compose up -d --pull
