name: Deploy DERS API to Dev Server

on:
  workflow_call:
    secrets:
      DERS_AZURE_STORAGE_CONNECTION_STRING:
        required: true
      DERS_SECURITY_FIREBASE_SERVICE_KEY:
        required: true
      DEV_SERVER_PASSWORD:
        required: true
      DERS_EMAIL_API_PASSWORD:
        required: true
      DERS_EVENTS_API_PASSWORD:
        required: true
      DERS_CHECKINS_API_PASSWORD:
        required: true
      DERS_BADGE_GENERATOR_PASSWORD:
        required: true
      DERS_QR_GENERATOR_PASSWORD:
        required: true
      DERS_IDENTITIES_API_PASSWORD:
        required: true
      DERS_AUTHORITIES_API_PASSWORD:
        required: true
      DERS_REPORTS_API_PASSWORD:
        required: true
      DERS_DOCUMENTS_API_PASSWORD:
        required: true
      DERS_REGISTRATIONS_API_PASSWORD:
        required: true
      DERS_POSTMASTER_MAIL_PASSWORD:
        required: true
      DERS_MAILGUN_SECRET:
        required: true
      DERS_MAILING_DB_PASSWORD:
        required: true
      DERS_GATEWAY:
        required: true
      DERS_IFRAME_URL:
        required: true
      DERS_EMAIL_API_URL:
        required: true
    inputs:
      PROJECT_NAME:
        type: string
        required: true

jobs:
  deploy-latest-release-on-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Execute docker-compose remotely via ssh
        uses: appleboy/ssh-action@master
        env:
          IMAGE_NAME: sastechnologies/${{ inputs.PROJECT_NAME }}:latest
          DERS_EVENTS_API_PASSWORD: ${{ secrets.DERS_EVENTS_API_PASSWORD }}
          DERS_CHECKINS_API_PASSWORD: ${{ secrets.DERS_CHECKINS_API_PASSWORD }}
          DERS_BADGE_GENERATOR_PASSWORD: ${{ secrets.DERS_BADGE_GENERATOR_PASSWORD }}
          DERS_QR_GENERATOR_PASSWORD: ${{ secrets.DERS_QR_GENERATOR_PASSWORD }}
          DERS_IDENTITIES_API_PASSWORD: ${{ secrets.DERS_IDENTITIES_API_PASSWORD }}
          DERS_DOCUMENTS_API_PASSWORD: ${{ secrets.DERS_DOCUMENTS_API_PASSWORD }}
          DERS_AUTHORITIES_API_PASSWORD: ${{ secrets.DERS_AUTHORITIES_API_PASSWORD }}
          DERS_REGISTRATIONS_API_PASSWORD: ${{ secrets.DERS_REGISTRATIONS_API_PASSWORD }}
          DERS_SECURITY_FIREBASE_SERVICE_KEY: ${{ secrets.DERS_SECURITY_FIREBASE_SERVICE_KEY }}
          DERS_AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.DERS_AZURE_STORAGE_CONNECTION_STRING }}
          DERS_POSTMASTER_MAIL_PASSWORD: ${{ secrets.DERS_POSTMASTER_MAIL_PASSWORD }}
          DERS_MAILGUN_SECRET: ${{ secrets.DERS_MAILGUN_SECRET }}
          DERS_MAILING_DB_PASSWORD: ${{ secrets.DERS_MAILING_DB_PASSWORD }}
          PUBLIC_DERS_EVENTS_API_PASSWORD: ${{ secrets.DERS_EVENTS_API_PASSWORD }}
          PUBLIC_DERS_GATEWAY: ${{ secrets.DERS_GATEWAY }}
          PUBLIC_DERS_DOCUMENTS_API_PASSWORD: ${{ secrets.DERS_DOCUMENTS_API_PASSWORD }}
          PUBLIC_DERS_REGISTRATIONS_API_PASSWORD: ${{ secrets.DERS_REGISTRATIONS_API_PASSWORD }}
          DERS_REPORTS_API_PASSWORD: ${{ secrets.DERS_REPORTS_API_PASSWORD }}
          DERS_GATEWAY_URL: ${{ secrets.DERS_GATEWAY }}
          DERS_IFRAME_URL: ${{ secrets.DERS_IFRAME_URL }}
          DERS_EMAIL_API_URL: ${{ secrets.DERS_EMAIL_API_URL }}
          DERS_EMAIL_API_PASSWORD: ${{ secrets.DERS_EMAIL_API_PASSWORD }}
        with:
          host: 165.22.89.92
          username: github-actions
          password: ${{ secrets.DEV_SERVER_PASSWORD }}
          envs: IMAGE_NAME,DERS_SECURITY_FIREBASE_SERVICE_KEY,DERS_AZURE_STORAGE_CONNECTION_STRING,DERS_EVENTS_API_PASSWORD,$DERS_AUTHORITIES_API_PASSWORD,DERS_DOCUMENTS_API_PASSWORD,DERS_REGISTRATIONS_API_PASSWORD,DERS_POSTMASTER_MAIL_PASSWORD,DERS_MAILGUN_SECRET,DERS_MAILING_DB_PASSWORD,PUBLIC_DERS_EVENTS_API_PASSWORD,PUBLIC_DERS_GATEWAY,PUBLIC_DERS_DOCUMENTS_API_PASSWORD,PUBLIC_DERS_REGISTRATIONS_API_PASSWORD,DERS_REPORTS_API_PASSWORD,DERS_CHECKINS_API_PASSWORD,DERS_IDENTITIES_API_PASSWORD,DERS_QR_GENERATOR_PASSWORD,DERS_BADGE_GENERATOR_PASSWORD,DERS_GATEWAY_URL,DERS_EMAIL_API_PASSWORD,DERS_EMAIL_API_URL,DERS_IFRAME_URL
          script: |
            export IMAGE_NAME=$IMAGE_NAME
            export DERS_SECURITY_FIREBASE_SERVICE_KEY=$DERS_SECURITY_FIREBASE_SERVICE_KEY
            export DERS_AZURE_STORAGE_CONNECTION_STRING=$DERS_AZURE_STORAGE_CONNECTION_STRING
            export DERS_AUTHORITIES_API_PASSWORD=$DERS_AUTHORITIES_API_PASSWORD
            export DERS_EMAIL_API_URL=$DERS_EMAIL_API_URL
            export DERS_IFRAME_URL=$DERS_IFRAME_URL
            export DERS_GATEWAY_URL=$DERS_GATEWAY_URL
            export DERS_EMAIL_API_PASSWORD=$DERS_EMAIL_API_PASSWORD
            export DERS_EVENTS_API_PASSWORD=$DERS_EVENTS_API_PASSWORD
            export DERS_CHECKINS_API_PASSWORD=$DERS_CHECKINS_API_PASSWORD
            export DERS_BADGE_GENERATOR_PASSWORD=$DERS_BADGE_GENERATOR_PASSWORD
            export DERS_QR_GENERATOR_PASSWORD=$DERS_QR_GENERATOR_PASSWORD
            export DERS_IDENTITIES_API_PASSWORD=$DERS_IDENTITIES_API_PASSWORD
            export DERS_DOCUMENTS_API_PASSWORD=$DERS_DOCUMENTS_API_PASSWORD
            export DERS_REGISTRATIONS_API_PASSWORD=$DERS_REGISTRATIONS_API_PASSWORD
            export DERS_REPORTS_API_PASSWORD=$DERS_REPORTS_API_PASSWORD
            export DERS_POSTMASTER_MAIL_PASSWORD=$DERS_POSTMASTER_MAIL_PASSWORD
            export DERS_MAILGUN_SECRET=$DERS_MAILGUN_SECRET
            export DERS_MAILING_DB_PASSWORD=$DERS_MAILING_DB_PASSWORD
            export PUBLIC_DERS_EVENTS_API_PASSWORD=$PUBLIC_DERS_EVENTS_API_PASSWORD
            export PUBLIC_DERS_GATEWAY=$PUBLIC_DERS_GATEWAY
            export PUBLIC_DERS_DOCUMENTS_API_PASSWORD=$PUBLIC_DERS_DOCUMENTS_API_PASSWORD
            export PUBLIC_DERS_REGISTRATIONS_API_PASSWORD=$PUBLIC_DERS_REGISTRATIONS_API_PASSWORD
            cd /opt/ders
            docker compose down
            docker image rm $IMAGE_NAME
            docker compose up -d
            cd /opt/proxy-manager
            docker compose restart
