name: Build Release Docker Image

on:
  workflow_call:
    secrets:
      # Secrets required by all APIs to pull dependencies from artifactory.sas-technologies.ro
      SAS_ARTIFACTORY_USER:
        required: true
      SAS_ARTIFACTORY_PASSWORD:
        required: true
      # Secrets required by all APIs to push built docker images to DockerHub
      DOCKERHUB_TOKEN:
        required: true
      DOCKERHUB_USERNAME:
        required: true
      # Secrets required by Documents Uploader API during tests
      AZURE_STORAGE_CONNECTION_STRING_TEST:
        required: false
      # Secrets required by API Identities during tests
      DERS_SECURITY_FIREBASE_SERVICE_KEY:
        required: false
      DERS_FIREBASE_API_KEY:
        required: false
      DERS_TEST_SECURITY_FIREBASE_SERVICE_KEY:
        required: false

jobs:

  publish-release-to-dockerhub:

    runs-on: ubuntu-latest

    env:
      SAS_ARTIFACTORY_USER: ${{ secrets.SAS_ARTIFACTORY_USER }}
      SAS_ARTIFACTORY_PASSWORD: ${{ secrets.SAS_ARTIFACTORY_PASSWORD }}
      AZURE_STORAGE_CONNECTION_STRING_TEST: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING_TEST }}
      DERS_FIREBASE_API_KEY: ${{ secrets.DERS_FIREBASE_API_KEY }}
      DERS_SECURITY_FIREBASE_SERVICE_KEY: ${{ secrets.DERS_SECURITY_FIREBASE_SERVICE_KEY }}
      DERS_TEST_SECURITY_FIREBASE_SERVICE_KEY: ${{ secrets.DERS_TEST_SECURITY_FIREBASE_SERVICE_KEY }}

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      -
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      -
        name: Pump Patch Version
        run: ./gradlew :bumpPatch --scan

      -
        name: Set git configuration
        run: |
          git config --global user.name 'Sebastian Rapa'
          git config --global user.email 'sebastian.rapa@sas-technologies.ro'
      -
        name: Commit & Push Version Pump
        run: |
          git commit -am "Automated Version Pump"
          git push

      -
        name: Add Project Name & Version to GitHub environment
        run: |
          echo "PROJECT_NAME=$(git rev-parse --show-toplevel | awk -F / '{print $NF}')" >> $GITHUB_ENV
          echo "PROJECT_VERSION=$(./gradlew properties --no-daemon --console=plain -q | grep "^version:" | awk '{printf $2}')" >> $GITHUB_ENV

      -
        name: Build Docker Image with version tag
        run: |
          ./gradlew bootBuildImage --imageName sastechnologies/${{ env.PROJECT_NAME }}:${{ env.PROJECT_VERSION }} -x test --info

      -
        name: Build Docker Image with latest tag
        run: |
          ./gradlew bootBuildImage --imageName sastechnologies/${{ env.PROJECT_NAME }}:latest -x test --info

      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Push versioned docker image to DockerHub
        run: docker push sastechnologies/${{ env.PROJECT_NAME }}:${{ env.PROJECT_VERSION }}

      -
        name: Push latest docker image to DockerHub
        run: docker push sastechnologies/${{ env.PROJECT_NAME }}:latest
