name: Dispatch Update Event to Version Catalog

on:
  workflow_call:
    inputs:
      LIBRARY_NAME:
        type: string
        required: true
    secrets:
      BEARER_TOKEN:
        required: true

jobs:
  dispatch-update-event:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch Library version
        run: |
          echo "LIBRARY_VERSION=$(grep "^version =" build.gradle.kts| cut -d ' ' -f3 | sed 's/\"//' | sed 's/\"//')" >> $GITHUB_ENV
      - name: Dispatch Update of Library
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.BEARER_TOKEN }}" \
          https://api.github.com/repos/sas-technologies/ders-kotlin-spring-version-catalog/actions/workflows/updateLibVersion.yml/dispatches \
          -d '{"ref":"master","inputs":{"libName":"${{ inputs.LIBRARY_NAME }}", "libVersion":"${{ env.LIBRARY_VERSION }}"}'