name: Upgrade Version Catalog

on:
  workflow_call:
    inputs:
      CATALOG_VERSION:
        type: string
        required: true
        description: 'The version of the catalog to upgrade to'

jobs:
  upgrade-version-catalog:
    runs-on: ubuntu-latest
    env:
      NEW_CATALOG_VERSION: ${{ inputs.CATALOG_VERSION }}
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Logging inputs
        run: |
          echo "New version of catalog that is upgrading to: $NEW_CATALOG_VERSION"

      - name: Run upgrade script
        run: bash scripts/upgradeVersionCatalog.sh $NEW_CATALOG_VERSION

      - name: Set git configuration
        run: |
          git config --global user.name 'Sebastian Rapa'
          git config --global user.email 'sebastian.rapa@sas-technologies.ro'

      - name: Commit & Push Version Pump
        run: |
          git commit -am "Automated upgrade of Version Catalog to version $NEW_CATALOG_VERSION"
          git push