name: SAS Technologies CI CD for Releases

on:
  workflow_call:
    secrets:
      SAS_ARTIFACTORY_USER:
        required: true
      SAS_ARTIFACTORY_PASSWORD:
        required: true
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:

  publish-snapshot-to-dockerhub:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Setup Private Artifactory Credentials
        uses: s4u/maven-settings-action@v2.5.0
        with:
          servers: |
            [{
              "id": "archiva.internal",
              "username": "${{ secrets.SAS_ARTIFACTORY_USER }}",
              "password": "${{ secrets.SAS_ARTIFACTORY_PASSWORD }}"},
            {
              "id": "archiva.snapshots",
              "username": "${{ secrets.SAS_ARTIFACTORY_USER }}",
              "password": "${{ secrets.SAS_ARTIFACTORY_PASSWORD }}"
            }]
      -
        name: Build jar File
        run: mvn -B package

      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Fetch Project and Branch Names
        run: |
          echo "BRANCH_NAME=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p' | awk '{ gsub("/","-",$0); print }')-SNAPSHOT" >> $GITHUB_ENV
          echo "PROJECT_NAME=$(git rev-parse --show-toplevel | awk -F / '{print $NF}')" >> $GITHUB_ENV
      -
        name: Build and Push Docker Image with Branch Snapshot as tag
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: sastechnologies/${{ env.PROJECT_NAME }}:${{ env.BRANCH_NAME }}