name: SAS Technologies CI CD for Releases

on:
  workflow_call:
    secrets:
      SAS_ARTIFACTORY_USER:
        required: true
      SAS_ARTIFACTORY_PASSWORD:
        required: true
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:

  publish-release-to-dockerhub:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      -
        name: Setup Private Artifactory Credentials
        uses: s4u/maven-settings-action@v2.5.0
        with:
          servers: |
            [{
              "id": "archiva.internal",
              "username": "${{ secrets.SAS_ARTIFACTORY_USER }}",
              "password": "${{ secrets.SAS_ARTIFACTORY_PASSWORD }}"},
            {
              "id": "archiva.snapshots",
              "username": "${{ secrets.SAS_ARTIFACTORY_USER }}",
              "password": "${{ secrets.SAS_ARTIFACTORY_PASSWORD }}"
            }]

      -
        name: Test Project
        run: ./gradlew test

      -
        name: Fetch Merged Branch Info
        env:
          BRANCH_NAME: ${{ github.head_ref }}
        run: |
          echo "MERGED_BRANCH_TYPE=$(echo $BRANCH_NAME | awk -F / '{ print tolower($1)}')" >> $GITHUB_ENV

      -
        name: Print Merged Branch Info
        env:
          BRANCH_NAME: ${{ github.head_ref }}
          BRANCH_TYPE: ${{ env.MERGED_BRANCH_TYPE }}
        run: |
          echo "Merged branch type: $BRANCH_TYPE"
          echo "Merged branch name: $BRANCH_NAME"
      -
        name: Pump Version if Patch
        if: ${{ env.MERGED_BRANCH_TYPE == 'hotfix' }}
        run: ./gradlew :bumpPatch

      -
        name: Pump Version if Minor
        if: ${{ env.MERGED_BRANCH_TYPE == 'minor-release' }}
        run: ./gradlew :bumpMinor

      -
        name: Pump Version if Major
        if: ${{ env.MERGED_BRANCH_TYPE == 'major-release' }}
        run: ./gradlew :bumpMajor

      -
        name: Set git configuration
        run: |
          git config --global user.name 'Sebastian Rapa'
          git config --global user.email 'sebastian.rapa@sas-technologies.ro'
      -
        name: Commit & Push Version Pump
        run: |
          git commit -am "Automated Version Pump"
          git push

      -
        name: Build jar File
        run: ./gradlew build -x test

      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Fetch Project and Branch Names
        run: |
          echo "PROJECT_NAME=$(git rev-parse --show-toplevel | awk -F / '{print $NF}')" >> $GITHUB_ENV
          echo "PROJECT_VERSION=$(./gradlew properties --no-daemon --console=plain -q | grep "^version:" | awk '{printf $2}')" >> $GITHUB_ENV

      -
        name: Build and Push Version
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: sastechnologies/${{ env.PROJECT_NAME }}:${{ env.PROJECT_VERSION }}

      -
        name: Build and Push latest
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: sastechnologies/${{ env.PROJECT_NAME }}:latest
