name: Sonar Qube Code Check
on:
  workflow_call:
    secrets:
      SONAR_PROJECT:
        required: true
      SONAR_TOKEN:
        required: true
      SONAR_HOST_URL:
        required: true
jobs:
  sonar-scanner:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}